# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SensorTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SensorTest
  pod 'RNSensors', :path => '../node_modules/react-native-sensors'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'RCTText',
    'RCTImage',
    'DevSupport',
   # 'CxxBridge',
    'RCTWebSocket',
    'RCTNetwork',
    'RCTLinkingIOS'
  ]

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  target 'SensorTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SensorTest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SensorTest-tvOS

  target 'SensorTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
